plugins {
    id 'java'
}

group = 'com.leathershorts.alltheshi'
version = '1.0-SNAPSHOT'

sourceCompatibility = JavaVersion.VERSION_17
targetCompatibility = JavaVersion.VERSION_17

repositories {
    mavenCentral()
}

dependencies {
    // JavaPoet handles the syntax-safe code generation blocks
    implementation 'com.squareup:javapoet:1.13.0'
}